version: '3'
services:
  go:
    container_name: 'hello-go'
    build:
      context: ./go
    ports:
        - 8000:8000
  redis:
    image: redis:latest
    volumes:
        - ./redis/data:/data
    command: redis-server --appendonly yes